const EDGE={events:[],markets:[],edges:[],movers:[],racing:[],stats:{}};
async function loadEdgeData(){try{const r=await fetch('data/edge-data.json?'+Date.now());if(!r.ok)throw new Error('data');return await r.json()}catch(e){return EDGE}}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function pct(v,d=1){return Number.isFinite(Number(v))?(Number(v)*100).toFixed(d)+'%':'—'}
function pp(v,d=1){return Number.isFinite(Number(v))?(Number(v)).toFixed(d)+' pp':'—'}
function price(v){return Number.isFinite(Number(v))?'$'+Number(v).toFixed(2):'—'}
function ev(v){return Number.isFinite(Number(v))?(Number(v)*100).toFixed(1)+'%':'—'}
function eventMap(d){return new Map((d.events||[]).map(x=>[x.id,x]))}
function modelled(d){return (d.markets||[]).filter(x=>Number.isFinite(Number(x.model_probability)))}
function renderNavStatus(d){document.querySelectorAll('[data-live]').forEach(x=>x.textContent=d.live?'DATA LIVE':'DATA PENDING')}
async function pageLoad(kind){const d=await loadEdgeData();renderNavStatus(d);if(kind==='index')renderHome(d);if(kind==='edges')renderEdges(d);if(kind==='events')renderEvents(d);if(kind==='sports')renderSports(d);if(kind==='racing')renderRacing(d);if(kind==='movers')renderMovers(d);if(kind==='watchlist')renderWatchlist(d)}
function renderHome(d){const st=d.stats||{};const nums=[st.events||0,st.markets||0,st.edges||0,st.avg_edge==null?'—':pp(st.avg_edge),st.sports||0,st.meetings||0];document.querySelectorAll('[data-kpi]').forEach((x,i)=>x.textContent=nums[i]??'—');const map=eventMap(d), rows=(d.markets||[]).filter(x=>Number.isFinite(Number(x.edge_probability_points))).sort((a,b)=>b.edge_probability_points-a.edge_probability_points).slice(0,12);const el=document.getElementById('homeEdges');if(el)el.innerHTML=rows.length?rows.map(x=>{const e=map.get(x.event_id)||{};return `<tr><td>${esc((e.home||'')+' v '+(e.away||''))}</td><td>${esc(x.market)} · ${esc(x.selection)}</td><td>${price(x.best_price)}</td><td>${pct(x.model_probability)}</td><td>${pct(x.market_fair_probability)}</td><td class="green">${pp(x.edge_probability_points)}</td></tr>`}).join(''):`<tr><td colspan="6" class="muted">No modelled edges yet. Connect an odds API, then add sport-specific probability models.</td></tr>`}
function renderEdges(d){const map=eventMap(d),rows=(d.markets||[]).filter(x=>Number.isFinite(Number(x.edge_probability_points))).sort((a,b)=>b.edge_probability_points-a.edge_probability_points);const el=document.getElementById('edgeRows');if(!el)return;el.innerHTML=rows.length?rows.map(x=>{const e=map.get(x.event_id)||{};return `<div class="data-row"><span>${esc((e.home||'')+' v '+(e.away||''))}</span><span>${esc(x.market)} · ${esc(x.selection)}</span><span>${price(x.best_price)}</span><span>${pct(x.model_probability)}</span><span>${pp(x.edge_probability_points)}</span><b class="green">${esc(x.confidence||'—')}</b></div>`}).join(''):`<div class="empty">No modelled edges yet. The live market layer is ready; probability models are the next layer.</div>`}
function renderEvents(d){const el=document.getElementById('eventRows');if(!el)return;el.innerHTML=(d.events||[]).slice().sort((a,b)=>String(a.commence_time).localeCompare(String(b.commence_time))).map(x=>`<div class="data-row"><span>${esc(x.league||x.sport||'')}</span><span>${esc(x.home||'')} v ${esc(x.away||'')}</span><span>${esc(x.commence_time||'')}</span><b>${(d.markets||[]).filter(m=>m.event_id===x.id).length}</b></div>`).join('')||'<div class="empty">No live events loaded.</div>'}
function renderSports(d){const counts={};(d.events||[]).forEach(e=>counts[e.sport]=(counts[e.sport]||0)+1);const el=document.getElementById('sportRows');if(!el)return;el.innerHTML=Object.entries(counts).sort((a,b)=>b[1]-a[1]).map(([s,n])=>`<div class="card"><small>SPORT</small><b>${esc(s)}</b><span>${n} events · ${(d.markets||[]).filter(m=>m.event_id && (d.events||[]).some(e=>e.id===m.event_id&&e.sport===s)).length} markets</span></div>`).join('')||'<div class="empty">No sports data loaded.</div>'}
function renderRacing(d){const el=document.getElementById('racingRows');if(el)el.innerHTML=(d.racing||[]).length?d.racing.map(x=>`<div class="data-row"><span>${esc(x.meeting||'')}</span><span>${esc(x.race||'')}</span><span>${esc(x.runner||'')}</span><span>${price(x.price)}</span><b>${pp(x.edge_probability_points)}</b></div>`).join(''):'<div class="empty">Racing connector not configured yet. Sports market data is the first live layer in V0.2.</div>'}
function renderMovers(d){const el=document.getElementById('moverRows');if(el)el.innerHTML=(d.movers||[]).map(x=>`<div class="data-row"><span>${esc(x.selection||'')}</span><span>${esc(x.bookmaker||'')}</span><span>${price(x.old_price)} → ${price(x.new_price)}</span><b>${esc(x.change_pct??'—')}%</b></div>`).join('')||'<div class="empty">Price-movement history will populate once consecutive snapshots are available.</div>'}
function renderWatchlist(d){const el=document.getElementById('watchRows');if(el)el.innerHTML='<div class="empty">Watchlist storage will be added after the live market schema is stable.</div>'}
